/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as PromosRouteImport } from './routes/promos'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminSponsorsRouteImport } from './routes/admin.sponsors'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminFeedRouteImport } from './routes/admin.feed'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as EventsEventIdIndexRouteImport } from './routes/events.$eventId.index'
import { Route as EventsEventIdEnterRouteImport } from './routes/events.$eventId.enter'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosRoute = PromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedRoute = AdminFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdEnterRoute = EventsEventIdEnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => EventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/promos': typeof PromosRoute
  '/tracker': typeof TrackerRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feed': typeof AdminFeedRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/enter': typeof EventsEventIdEnterRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/promos': typeof PromosRoute
  '/tracker': typeof TrackerRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feed': typeof AdminFeedRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/enter': typeof EventsEventIdEnterRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/promos': typeof PromosRoute
  '/tracker': typeof TrackerRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feed': typeof AdminFeedRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/enter': typeof EventsEventIdEnterRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/feed'
    | '/gallery'
    | '/profile'
    | '/promos'
    | '/tracker'
    | '/admin/events'
    | '/admin/feed'
    | '/admin/promos'
    | '/admin/sponsors'
    | '/events/$eventId'
    | '/admin/'
    | '/events/'
    | '/events/$eventId/enter'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/gallery'
    | '/profile'
    | '/promos'
    | '/tracker'
    | '/admin/events'
    | '/admin/feed'
    | '/admin/promos'
    | '/admin/sponsors'
    | '/admin'
    | '/events'
    | '/events/$eventId/enter'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/feed'
    | '/gallery'
    | '/profile'
    | '/promos'
    | '/tracker'
    | '/admin/events'
    | '/admin/feed'
    | '/admin/promos'
    | '/admin/sponsors'
    | '/events/$eventId'
    | '/admin/'
    | '/events/'
    | '/events/$eventId/enter'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  GalleryRoute: typeof GalleryRoute
  ProfileRoute: typeof ProfileRoute
  PromosRoute: typeof PromosRoute
  TrackerRoute: typeof TrackerRoute
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promos': {
      id: '/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof PromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feed': {
      id: '/admin/feed'
      path: '/feed'
      fullPath: '/admin/feed'
      preLoaderRoute: typeof AdminFeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/enter': {
      id: '/events/$eventId/enter'
      path: '/enter'
      fullPath: '/events/$eventId/enter'
      preLoaderRoute: typeof EventsEventIdEnterRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFeedRoute: typeof AdminFeedRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminFeedRoute: AdminFeedRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsEventIdRouteChildren {
  EventsEventIdEnterRoute: typeof EventsEventIdEnterRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdEnterRoute: EventsEventIdEnterRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  GalleryRoute: GalleryRoute,
  ProfileRoute: ProfileRoute,
  PromosRoute: PromosRoute,
  TrackerRoute: TrackerRoute,
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
